# Generated by Django 2.1 on 2018-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('index_number', models.IntegerField(primary_key=True, serialize=False)),
                ('index_str', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=30)),
                ('distance', models.IntegerField()),
                ('all_tur', models.CharField(max_length=30)),
                ('inn_out', models.CharField(max_length=30)),
                ('str_rnd', models.CharField(max_length=30)),
                ('friendly_course', models.CharField(max_length=30)),
                ('friendly_distance', models.CharField(max_length=30)),
                ('c_d_attr', models.IntegerField()),
                ('c_d_offs', models.IntegerField()),
                ('m', models.IntegerField()),
                ('c', models.IntegerField()),
            ],
        ),
    ]
