# Generated by Django 2.1 on 2018-09-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='c',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='index_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courses',
            name='m',
            field=models.FloatField(),
        ),
    ]
