# Generated by Django 2.1 on 2018-09-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180908_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='index_str',
        ),
    ]
