# Generated by Django 2.1 on 2018-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180908_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='index_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
