# Generated by Django 2.1 on 2018-09-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180908_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='index_str',
        ),
        migrations.AlterField(
            model_name='courses',
            name='all_tur',
            field=models.CharField(choices=[('a', 'a'), ('t', 't')], default='t', max_length=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='inn_out',
            field=models.CharField(choices=[('o', 'o'), ('i', 'i'), ('-', '-')], default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='courses',
            name='str_rnd',
            field=models.CharField(choices=[('s', 's'), ('r', 'r')], default='r', max_length=30),
        ),
    ]
